name: CD

on:
  workflow_dispatch:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dist-build:
    name: Distribution Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build wheels
        run: pipx run build
      - uses: actions/upload-artifact@v4
        with:
          path: dist
      - name: Check wheels
        run: pipx run twine check dist/*

  dist-test:
    name: Distribution Test
    needs: [dist-build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      - name: List Contents
        run: |
          ls -ltrh
          ls -ltrh dist
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          skip-existing: true
      - name: Check pypi packages
        run: |
          sleep 3
          python -m pip install --upgrade pip

          echo "=== Testing wheel file ==="
          python -m pip install --extra-index-url https://test.pypi.org/simple --upgrade --pre braingeneers
          python -c "import braingeneers; print(braingeneers.__version__)"
          echo "=== Done testing wheel file ==="

          echo "=== Testing source tar file ==="
          python -m pip uninstall --yes braingeneers
          python -m pip install --extra-index-url https://test.pypi.org/simple --upgrade --pre --no-binary=:all: braingeneers
          python -c "import braingeneers; print(braingeneers.__version__)"
          echo "=== Done testing source tar file ==="





